= Proyecto Primer Parcial Instrumentación virtual
Paola Jocelyn Salazar Hernandez <salazarpaola@outlook.com>
:doctype: book
:toc: 
:imagesdir: Images
:sectnums: 
:toclevels: 3
:chapter-label: Section

== Project description

No description found (add content in project description)

== Code component descriptions

=== DQMH(R) modules

This section describes DQMH(R) module responsibilities and relationships.

==== Preamble

A DQMH module is the main component of an architecture based on DQMH(R) framework. A DQMH module is used to implement a section of the application that has one responsibility.

DQMH(R) framework defines two different type of DQMH module.  

====
*Singleton:*

A Singleton DQMH module can have only one instance running at any given time.
====

====
*Cloneable:*

A Cloneable DQMH module can have one or multiple instances running in parallel.
====

DQMH(R) framework defines two different ways to carry data throughout the application and with both other DQMH modules and non-DQMH based code.

====
*Request events:*

A request is a code that fires an event requesting the DQMH module to do something. Multiple locations in the code can send events to the DQMH module.

Request events are many-to-one.

Requests are usually named using imperative tense.
====

====
*Broadcast events:*

A broadcast is a code that fires an event broadcasting that the DQMH module did something. Multiple Event Structures can register to handle the Broadcast Events.

Broadcast Events are one-to-many.

Broadcasts are usually named using past tense or passive voice.
====

NOTE: Refer to the DQMH(R) framework official http://delacor.com/documentation/dqmh-html/[documentation] to find more details on how the framework works


The following section gives you details on the project architecture relying on this framework.
It gives you an overview of the modules' interaction and detailed information on each module.

Graphs used in this section have the following legend:

*Components:*


[graphviz, format="png", align="center"]
....
digraph G371093 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DQMH module / Lvlib"[color=black shape=component]
"Vi"[color=skyblue shape=note]
}
....

*Events:*

[graphviz, format="png", align="center"]
....
digraph G381624 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
" "[color=white shape=box]
"  "[color=white shape=box]
"   "[color=white shape=box]
"    "[color=white shape=box]
" " -> "  " [label="Request to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"   " -> "    " [label="Broadcast from a DQMH module" dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
}
....

*Start and Stop module callers:*

[graphviz, format="png", align="center"]
....
digraph G887769 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module
caller"[color=black shape=component]
"Start Module"[color=yellowgreen shape=note]
"Start Module" -> "Start Module
caller" [label="Called by" dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
}
....

[graphviz, format="png", align="center"]
....
digraph G56960 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Stop Module
caller"[color=black shape=component]
"Stop Module"[color=tomato shape=note]
"Stop Module" -> "Stop Module
caller" [label="Called by" dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....


==== Modules overview

This project contains the following modules.

.Modules list
|===
|Singleton|Cloneable

|<<Configuration.lvlib>>
|

|<<Messages.lvlib>>
|

|<<Monedas.lvlib>>
|

|<<Products.lvlib>>
|

|<<UI.lvlib>>
|
|===

This graph represents the links between all DQMH modules.

[graphviz, format="png", align="center"]
....
digraph G68872 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=black shape=component]
"Configuration"[color=black shape=component]
"Messages"[color=black shape=component]
"Monedas"[color=black shape=component]
"Products"[color=black shape=component]
"Configuration" -> "Configuration" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Configuration" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Messages" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
}
....


==== Configuration.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G814010 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Configuration API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Configuration"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Configuration API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Configuration" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Configuration API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Configuration.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Configuration API.vi

|<<Configuration.lvlib:Stop Module.vi>>
|Configuration.lvlib:Handle Exit.vi +
Test Configuration API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G943564 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Configuration"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Configuration API"[color=skyblue shape=note]
"Monedas"[color=black shape=component]
"Products"[color=black shape=component]
"UI" -> "Configuration" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Configuration API" -> "Configuration" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Configuration" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Test Configuration API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Configuration" -> "Configuration" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Monedas" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Products" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Configuration.lvlib:Show Panel.vi>>
|UI.lvlib:Main.vi +
Test Configuration API.vi

|<<Configuration.lvlib:Hide Panel.vi>>
|Test Configuration API.vi

|<<Configuration.lvlib:Get Module Execution Status.vi>>
|Configuration.lvlib:Start Module.vi +
Configuration.lvlib:Obtain Broadcast Events for Registration.vi

|<<Configuration.lvlib:Show Diagram.vi>>
|Test Configuration API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Configuration.lvlib:Module Did Init.vi>>
|Test Configuration API.vi

|<<Configuration.lvlib:Status Updated.vi>>
|Test Configuration API.vi

|<<Configuration.lvlib:Error Reported.vi>>
|Test Configuration API.vi

|<<Configuration.lvlib:Module Did Stop.vi>>
|Test Configuration API.vi

|<<Configuration.lvlib:Update Module Execution Status.vi>>
|Test Configuration API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Configuration.lvlib>>
|Configuration.lvlib:Get Module Execution Status.vi

|<<Monedas.lvlib>>
|Monedas.lvlib:Set Coins Values.vi

|<<Products.lvlib>>
|Products.lvlib:Set product.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Messages.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G51611 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Messages"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Mensajes API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Messages" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Mensajes API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Messages.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Mensajes API.vi

|<<Messages.lvlib:Stop Module.vi>>
|Messages.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Mensajes API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G49445 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Messages"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Mensajes API"[color=skyblue shape=note]
"Monedas"[color=black shape=component]
"Products"[color=black shape=component]
"UI" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Mensajes API" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Messages" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Messages" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Messages" -> "Messages" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Messages.lvlib:Show Panel.vi>>
|Test Mensajes API.vi

|<<Messages.lvlib:Hide Panel.vi>>
|Test Mensajes API.vi

|<<Messages.lvlib:Get Module Execution Status.vi>>
|Messages.lvlib:Start Module.vi +
Messages.lvlib:Obtain Broadcast Events for Registration.vi

|<<Messages.lvlib:Show Diagram.vi>>
|Test Mensajes API.vi

|<<Messages.lvlib:Publicar Mensaje.vi>>
|Monedas.lvlib:Main.vi +
Products.lvlib:Main.vi +
Products.lvlib:Sell product.vi +
UI.lvlib:Main.vi +
Test Mensajes API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Messages.lvlib:Module Did Init.vi>>
|

|<<Messages.lvlib:Status Updated.vi>>
|

|<<Messages.lvlib:Error Reported.vi>>
|

|<<Messages.lvlib:Module Did Stop.vi>>
|

|<<Messages.lvlib:Update Module Execution Status.vi>>
|
|===

.Used requests
|===
|Module|Brodcasts

|<<Messages.lvlib>>
|Messages.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Monedas.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G158226 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Monedas API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Monedas"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Monedas API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Monedas" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Monedas API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Monedas.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Monedas API.vi

|<<Monedas.lvlib:Stop Module.vi>>
|Monedas.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Monedas API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G441959 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Monedas"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Monedas API"[color=skyblue shape=note]
"Configuration"[color=black shape=component]
"Products"[color=black shape=component]
"Messages"[color=black shape=component]
"UI" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Monedas API" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Monedas" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Test Monedas API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Monedas" -> "Messages" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Monedas" -> "Monedas" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Monedas.lvlib:Show Panel.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Hide Panel.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Get Module Execution Status.vi>>
|Monedas.lvlib:Start Module.vi +
Monedas.lvlib:Obtain Broadcast Events for Registration.vi

|<<Monedas.lvlib:Show Diagram.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Coin pressed.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Set Coins Values.vi>>
|Configuration.lvlib:Main.vi +
Test Monedas API.vi

|<<Monedas.lvlib:Request_Crédito.vi>>
|Products.lvlib:Sell product.vi +
Test Monedas API.vi

|<<Monedas.lvlib:Reset Crédito.vi>>
|Products.lvlib:Sell product.vi +
Test Monedas API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Monedas.lvlib:Module Did Init.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Status Updated.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Error Reported.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Module Did Stop.vi>>
|Test Monedas API.vi

|<<Monedas.lvlib:Update Module Execution Status.vi>>
|Test Monedas API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Messages.lvlib>>
|Messages.lvlib:Publicar Mensaje.vi

|<<Monedas.lvlib>>
|Monedas.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== Products.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G12480 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"UI"[color=black shape=component]
"Test Products API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"Products"[color=black shape=component]
"Start Module" -> "UI" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Start Module" -> "Test Products API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "Products" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test Products API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<Products.lvlib:Start Module.vi>>
|UI.lvlib:Main.vi +
Test Products API.vi

|<<Products.lvlib:Stop Module.vi>>
|Products.lvlib:Handle Exit.vi +
UI.lvlib:Main.vi +
Test Products API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G501191 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Products"[color=slateblue shape=component]
"UI"[color=black shape=component]
"Test Products API"[color=skyblue shape=note]
"Configuration"[color=black shape=component]
"Messages"[color=black shape=component]
"Monedas"[color=black shape=component]
"UI" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Test Products API" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Configuration" -> "Products" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"Products" -> "Test Products API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"Products" -> "Messages" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Products" -> "Monedas" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"Products" -> "Products" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<Products.lvlib:Show Panel.vi>>
|Test Products API.vi

|<<Products.lvlib:Hide Panel.vi>>
|Test Products API.vi

|<<Products.lvlib:Get Module Execution Status.vi>>
|Products.lvlib:Start Module.vi +
Products.lvlib:Obtain Broadcast Events for Registration.vi

|<<Products.lvlib:Show Diagram.vi>>
|Test Products API.vi

|<<Products.lvlib:Set product.vi>>
|Configuration.lvlib:Main.vi +
Products.lvlib:Sell product.vi +
Test Products API.vi

|<<Products.lvlib:Product Selection.vi>>
|Test Products API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<Products.lvlib:Module Did Init.vi>>
|Test Products API.vi

|<<Products.lvlib:Status Updated.vi>>
|Test Products API.vi

|<<Products.lvlib:Error Reported.vi>>
|Test Products API.vi

|<<Products.lvlib:Module Did Stop.vi>>
|Test Products API.vi

|<<Products.lvlib:Update Module Execution Status.vi>>
|Test Products API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Messages.lvlib>>
|Messages.lvlib:Publicar Mensaje.vi

|<<Monedas.lvlib>>
|Monedas.lvlib:Request_Crédito.vi +
Monedas.lvlib:Reset Crédito.vi

|<<Products.lvlib>>
|Products.lvlib:Get Module Execution Status.vi +
Products.lvlib:Set product.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

==== UI.lvlib

*Type:* Singleton

*Responsibility*: No description found (add content in DQMH module lvlib description)

===== Module Start/Stop calls

[graphviz, format="png", align="center"]
....
digraph G96627 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module"[color=yellowgreen shape=note]
"Test UI API"[color=skyblue shape=note]
"Stop Module"[color=tomato shape=note]
"UI"[color=black shape=component]
"Start Module" -> "Test UI API" [dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
"Stop Module" -> "UI" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
"Stop Module" -> "Test UI API" [dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....

.Start and Stop module callers
|===
|Function|Callers

|<<UI.lvlib:Start Module.vi>>
|Test UI API.vi

|<<UI.lvlib:Stop Module.vi>>
|UI.lvlib:Handle Exit.vi +
Test UI API.vi
|===

===== Module relationship

[graphviz, format="png", align="center"]
....
digraph G315429 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"UI"[color=slateblue shape=component]
"Test UI API"[color=skyblue shape=note]
"Configuration"[color=black shape=component]
"Messages"[color=black shape=component]
"Test UI API" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"UI" -> "Test UI API" [label=" " dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
"UI" -> "Configuration" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "Messages" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
"UI" -> "UI" [label="   " dir=both color=forestgreen  arrowhead=onormal arrowtail=none style=filled penwidth=1];
}
....

.Requests callers
|===
|Request Name|Callers

|<<UI.lvlib:Show Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Hide Panel.vi>>
|Test UI API.vi

|<<UI.lvlib:Get Module Execution Status.vi>>
|UI.lvlib:Start Module.vi +
UI.lvlib:Obtain Broadcast Events for Registration.vi

|<<UI.lvlib:Show Diagram.vi>>
|Test UI API.vi
|===

.Broadcasts Listeners
|===
|Broadcast Name|Listeners

|<<UI.lvlib:Module Did Init.vi>>
|Test UI API.vi

|<<UI.lvlib:Status Updated.vi>>
|Test UI API.vi

|<<UI.lvlib:Error Reported.vi>>
|Test UI API.vi

|<<UI.lvlib:Module Did Stop.vi>>
|Test UI API.vi

|<<UI.lvlib:Update Module Execution Status.vi>>
|Test UI API.vi
|===

.Used requests
|===
|Module|Brodcasts

|<<Configuration.lvlib>>
|Configuration.lvlib:Show Panel.vi

|<<Messages.lvlib>>
|Messages.lvlib:Publicar Mensaje.vi

|<<UI.lvlib>>
|UI.lvlib:Get Module Execution Status.vi
|===

.Registred broadcast
|===
|Module|Brodcasts

|--
|--
|===

=== Libraries

This section describes the libraries contained in the project.

=== Classes

This section describes the classes contained in the project.

== VI descriptions

=== DQMH(R) modules

This section describes DQMH(R) modules events.

==== Configuration.lvlib

===== Configuration.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Configuration.lvlib_Start Module.vi.png
image::{imgpath}[Configuration.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Configuration.lvlib_Stop Module.vi.png
image::{imgpath}[Configuration.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Configuration.lvlib_Show Panel.vi.png
image::{imgpath}[Configuration.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Configuration.lvlib_Hide Panel.vi.png
image::{imgpath}[Configuration.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Configuration.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Configuration.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Configuration.lvlib_Show Diagram.vi.png
image::{imgpath}[Configuration.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Configuration.lvlib_Module Did Init.vi.png
image::{imgpath}[Configuration.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Configuration.lvlib_Status Updated.vi.png
image::{imgpath}[Configuration.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Configuration.lvlib_Error Reported.vi.png
image::{imgpath}[Configuration.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Configuration.lvlib_Module Did Stop.vi.png
image::{imgpath}[Configuration.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Configuration.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Configuration.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Configuration.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Messages.lvlib

===== Messages.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Messages.lvlib_Start Module.vi.png
image::{imgpath}[Messages.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Messages.lvlib_Stop Module.vi.png
image::{imgpath}[Messages.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Messages.lvlib_Show Panel.vi.png
image::{imgpath}[Messages.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Messages.lvlib_Hide Panel.vi.png
image::{imgpath}[Messages.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Messages.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Messages.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Messages.lvlib_Show Diagram.vi.png
image::{imgpath}[Messages.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Publicar Mensaje.vi

*Event type:* Request

:imgpath: Messages.lvlib_Publicar Mensaje.vi.png
image::{imgpath}[Messages.lvlib:Publicar Mensaje.vi]

*Description:*
++++
Publicar un mensaje en el modulo DQMH mensajes
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Messages.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Messages.lvlib_Module Did Init.vi.png
image::{imgpath}[Messages.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Messages.lvlib_Status Updated.vi.png
image::{imgpath}[Messages.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Messages.lvlib_Error Reported.vi.png
image::{imgpath}[Messages.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Messages.lvlib_Module Did Stop.vi.png
image::{imgpath}[Messages.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Messages.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Messages.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Messages.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Monedas.lvlib

===== Monedas.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Monedas.lvlib_Start Module.vi.png
image::{imgpath}[Monedas.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Monedas.lvlib_Stop Module.vi.png
image::{imgpath}[Monedas.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Show Panel.vi.png
image::{imgpath}[Monedas.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Hide Panel.vi.png
image::{imgpath}[Monedas.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Monedas.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Show Diagram.vi.png
image::{imgpath}[Monedas.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Coin pressed.vi

*Event type:* Request And Wait For Reply

:imgpath: Monedas.lvlib_Coin pressed.vi.png
image::{imgpath}[Monedas.lvlib:Coin pressed.vi]

*Description:*
++++
<b>Note</b>: This VI was renamed by the DQMH Rename Event utility. Make sure the VI Description is updated to reflect the new event name, then delete this comment.

Presionando los botones de monedas se va actualizando el credito correspondiente
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Set Coins Values.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Set Coins Values.vi.png
image::{imgpath}[Monedas.lvlib:Set Coins Values.vi]

*Description:*
++++
Se coloca la demoninación de la moneda y su valor a los botones
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Request_Crédito.vi

*Event type:* Request And Wait For Reply

:imgpath: Monedas.lvlib_Request_Crédito.vi.png
image::{imgpath}[Monedas.lvlib:Request_Crédito.vi]

*Description:*
++++
Obtener el credito en cualquier modulo
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Reset Crédito.vi

*Event type:* Request

:imgpath: Monedas.lvlib_Reset Crédito.vi.png
image::{imgpath}[Monedas.lvlib:Reset Crédito.vi]

*Description:*
++++
Resetea el valr de crédito después de una compra
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Monedas.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Module Did Init.vi.png
image::{imgpath}[Monedas.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Status Updated.vi.png
image::{imgpath}[Monedas.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Error Reported.vi.png
image::{imgpath}[Monedas.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Module Did Stop.vi.png
image::{imgpath}[Monedas.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Monedas.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Monedas.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Monedas.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== Products.lvlib

===== Products.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: Products.lvlib_Start Module.vi.png
image::{imgpath}[Products.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: Products.lvlib_Stop Module.vi.png
image::{imgpath}[Products.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: Products.lvlib_Show Panel.vi.png
image::{imgpath}[Products.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: Products.lvlib_Hide Panel.vi.png
image::{imgpath}[Products.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: Products.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[Products.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: Products.lvlib_Show Diagram.vi.png
image::{imgpath}[Products.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Set product.vi

*Event type:* Request

:imgpath: Products.lvlib_Set product.vi.png
image::{imgpath}[Products.lvlib:Set product.vi]

*Description:*
++++
Dibuja los productos en la tabla
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Products.lvlib:Product Selection.vi

*Event type:* Request

:imgpath: Products.lvlib_Product Selection.vi.png
image::{imgpath}[Products.lvlib:Product Selection.vi]

*Description:*
++++
es para poder seleccionar el producto
_____
Created using Delacor QMH Event Scripter 5.0.0.112.
++++

===== Products.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: Products.lvlib_Module Did Init.vi.png
image::{imgpath}[Products.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: Products.lvlib_Status Updated.vi.png
image::{imgpath}[Products.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: Products.lvlib_Error Reported.vi.png
image::{imgpath}[Products.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: Products.lvlib_Module Did Stop.vi.png
image::{imgpath}[Products.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== Products.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: Products.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[Products.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

==== UI.lvlib

===== UI.lvlib:Start Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Start Module.vi.png
image::{imgpath}[UI.lvlib:Start Module.vi]

*Description:*
++++
Launches the Module Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Stop Module.vi

*Event type:* Not a DQMH Event

:imgpath: UI.lvlib_Stop Module.vi.png
image::{imgpath}[UI.lvlib:Stop Module.vi]

*Description:*
++++
Send the Stop request to the Module's Main.vi.

If <b>Wait for Module to Stop?</b> is TRUE, this VI will wait until the module main VI stops, and will timeout at the <b>Timeout to Wait for Stop</b> value. This value defaults to "-1", which means the VI will not timeout, and will always wait until the module main VI stops before completing execution.

Note: The <b>Timeout to Wait for Stop</b> value is ignored if 'Wait for Module to Stop?' is set to FALSE.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Panel.vi.png
image::{imgpath}[UI.lvlib:Show Panel.vi]

*Description:*
++++
Send the Show Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Hide Panel.vi

*Event type:* Request

:imgpath: UI.lvlib_Hide Panel.vi.png
image::{imgpath}[UI.lvlib:Hide Panel.vi]

*Description:*
++++
Send the Hide Panel request to the Module's Main.vi.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Get Module Execution Status.vi

*Event type:* Request

:imgpath: UI.lvlib_Get Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Get Module Execution Status.vi]

*Description:*
++++
Fire the Get Module Execution Status request.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Show Diagram.vi

*Event type:* Request

:imgpath: UI.lvlib_Show Diagram.vi.png
image::{imgpath}[UI.lvlib:Show Diagram.vi]

*Description:*
++++
This VI tells the Module to show its block diagram to facilitate troubleshooting (add probes, breakpoints, highlight execution, etc).

_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Init.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Init.vi.png
image::{imgpath}[UI.lvlib:Module Did Init.vi]

*Description:*
++++
Send the Module Did Init event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Status Updated.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Status Updated.vi.png
image::{imgpath}[UI.lvlib:Status Updated.vi]

*Description:*
++++
Send the Status Updated event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Error Reported.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Error Reported.vi.png
image::{imgpath}[UI.lvlib:Error Reported.vi]

*Description:*
++++
Send the Error Reported event to any VI registered to listen to events from the owning module.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Module Did Stop.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Module Did Stop.vi.png
image::{imgpath}[UI.lvlib:Module Did Stop.vi]

*Description:*
++++
Send the Module Did Stop event to any VI registered to listen to this module's broadcast events.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

===== UI.lvlib:Update Module Execution Status.vi

*Event type:* Broadcast

:imgpath: UI.lvlib_Update Module Execution Status.vi.png
image::{imgpath}[UI.lvlib:Update Module Execution Status.vi]

*Description:*
++++
Broadcast event to specify whether or not the module is running.
_____
Based on Delacor QMH Project Template 5.0.0.82.
++++

=== Libraries

This section describes libraries public VIs.

=== Classes

This section describes classes public VIs.

== Legal Information

=== Document creation

This document has been generated using the following tools.

==== Antidoc

Project website: https://wovalab.gitlab.io/open-source/labview-doc-generator/[Antidoc] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Asciidoc for LabVIEW(TM)

Project website: https://wovalab.gitlab.io/open-source/asciidoc-toolkit/[Asciidoc toolkit] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Graph Builder

Project website: https://gitlab.com/cgambini/graph-builder[Graph Builder]

BSD 3-Clause License

Copyright (c) 2020, Cyril GAMBINI
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


=== Product used in the project

The documented project has been developed with the following products.

==== DQMH(R)

Copyright (C) 2015-2020 by Delacor, LLC. All Rights Reserved.

Find more details on https://delacor.com/products/dqmh/[Delacor] website

